name: Pipeline

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop, feature/*]
permissions:
  contents: write
  actions: read
  checks: write
  pull-requests: write

jobs:
  lint-commits:
    name: Run Commitlint Checks
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/commitlint.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  code-style:
    name: Run Linter Formatter
    uses: ./.github/workflows/linting.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
      commit_changes: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    secrets: inherit

  type-check:
    name: Run Type Checks
    uses: ./.github/workflows/typecheck.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
    secrets: inherit

  check-deps:
    name: Run Dependency Checks
    uses: ./.github/workflows/unused.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
    secrets: inherit

  docker-scan-deploy:
    permissions:
      contents: read
      packages: write
    name: Run Docker Scan & Deploy
    needs:
      - code-style
      - type-check
      - check-deps
    uses: ./.github/workflows/docker.yml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
    secrets: inherit

  all-passed:
    name: Check Build Status
    runs-on: ubuntu-latest
    needs:
      - lint-commits
      - code-style
      - type-check
      - check-deps
      - docker-scan-deploy
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Report Success
        run: echo "All required checks passed successfully."
